version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
configuration: Release
platform: Any CPU
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  include_nuget_references: true
  verbosity: minimal
