version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: dotnetCampus.SourceYard.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal